-- ==========================================
-- Roayti PostgreSQL Clean Export File
-- Generated for migration to new PostgreSQL database
-- ==========================================

-- Data for table: users (4 rows)
INSERT INTO public.users ("uid", "display_name", "username", "email", "photo_url", "banner_url", "bio", "role", "font_family", "terabox_link", "show_cloud_assets_publicly", "onboarding_completed", "links", "manual_badge", "created_at", "updated_at") VALUES ('user_master_01', 'أحمد محمود', 'ahmad_writer', 'ahmad@example.com', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150', '', 'كاتب ومؤلف روايات الفانتازيا والدراما التاريخية العربية، مهتم بسرد الملاحم والقصص الأسطورية.', 'admin', '', '', false, false, '[]'::jsonb, 'verified', '"2026-08-08T15:28:11.311Z"'::jsonb, '"2026-08-08T15:28:11.311Z"'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.users ("uid", "display_name", "username", "email", "photo_url", "banner_url", "bio", "role", "font_family", "terabox_link", "show_cloud_assets_publicly", "onboarding_completed", "links", "manual_badge", "created_at", "updated_at") VALUES ('user_sara_02', 'سارة النجار', 'sara_author', 'sara@example.com', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150', '', 'مؤلفة قصص الخيال والغموض، حائزة على عدة جوائز أدبية ومحبة للقراءة والتحليل.', 'verified_author', '', '', false, false, '[]'::jsonb, 'gold_writer', '"2026-08-08T15:28:11.311Z"'::jsonb, '"2026-08-08T15:28:11.311Z"'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.users ("uid", "display_name", "username", "email", "photo_url", "banner_url", "bio", "role", "font_family", "terabox_link", "show_cloud_assets_publicly", "onboarding_completed", "links", "manual_badge", "created_at", "updated_at") VALUES ('user_omar_03', 'عمر الفاروق', 'omar_reader', 'omar@example.com', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150', '', 'قارئ شغوف ومراجع للروايات العربية في منتدى الروايات.', 'user', '', '', false, false, '[]'::jsonb, 'reader_pro', '"2026-08-08T15:28:11.311Z"'::jsonb, '"2026-08-08T15:28:11.311Z"'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.users ("uid", "display_name", "username", "email", "photo_url", "banner_url", "bio", "role", "font_family", "terabox_link", "show_cloud_assets_publicly", "onboarding_completed", "links", "manual_badge", "created_at", "updated_at") VALUES ('user_layla_04', 'ليلى العمري', 'layla_novels', 'layla@example.com', 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150', '', 'شغوفة بسرد الحكايات والروايات الاجتماعية والأسطورية.', 'author', '', '', false, false, '[]'::jsonb, 'silver_writer', '"2026-08-08T15:28:11.311Z"'::jsonb, '"2026-08-08T15:28:11.311Z"'::jsonb) ON CONFLICT DO NOTHING;

-- Data for table: novels (4 rows)
INSERT INTO public.novels ("id", "author_uid", "author_name", "author_photo", "title", "genre", "summary", "cover_image", "status", "likes_count", "views_count", "shares_count", "language", "violence_level", "moral_tone", "font_family", "font_size", "text_align", "line_height", "previous_part_id", "terabox_link", "created_at", "updated_at") VALUES ('n_001', 'user_master_01', 'أحمد محمود', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150', 'ظل العرش المفقود', 'fantasy', 'ملحمة أدبية تحكي عن صراع الممالك القديمة والبحث عن التاج المفقود في أرض الأسرار والغموض، حيث يتصدى الفارس أدهم للقوى المظلمة لحماية عقيدته وشعبه.', 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=800', 'published', 142, 2890, 35, 'ar', 'moderate', 'heroic', 'var(--font-serif)', '1.125rem', 'right', '1.75', NULL, '', '"2026-08-08T15:28:11.319Z"'::jsonb, '"2026-08-08T15:28:11.319Z"'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.novels ("id", "author_uid", "author_name", "author_photo", "title", "genre", "summary", "cover_image", "status", "likes_count", "views_count", "shares_count", "language", "violence_level", "moral_tone", "font_family", "font_size", "text_align", "line_height", "previous_part_id", "terabox_link", "created_at", "updated_at") VALUES ('n_003', 'user_layla_04', 'ليلى العمري', 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150', 'صدى الكلمات والإلهام', 'drama', 'قصة إنسانية عميقة تتناول دراما العلاقات، التضحية، والبحث عن الذات عبر مختلف مراحل الحياة والتحديات الروحية.', 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?q=80&w=800', 'published', 215, 4120, 68, 'ar', 'none', 'inspirational', 'var(--font-serif)', '1.125rem', 'right', '1.75', NULL, '', '"2026-08-08T15:28:11.319Z"'::jsonb, '"2026-08-08T15:28:11.319Z"'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.novels ("id", "author_uid", "author_name", "author_photo", "title", "genre", "summary", "cover_image", "status", "likes_count", "views_count", "shares_count", "language", "violence_level", "moral_tone", "font_family", "font_size", "text_align", "line_height", "previous_part_id", "terabox_link", "created_at", "updated_at") VALUES ('n_004', 'user_master_01', 'أحمد محمود', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150', 'أرباب الأفق الأخبر', 'sci-fi', 'رحلة مستقبليّة عبر أبعاد الكون المظلم للبحث عن ملاذ جديد للبشرية بعد تحول مناخ الأرض واكتشاف مجرة غير مطروقة.', 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?q=80&w=800', 'published', 76, 1100, 12, 'ar', 'moderate', 'sci-fi', 'var(--font-serif)', '1.125rem', 'right', '1.75', NULL, '', '"2026-08-08T15:28:11.319Z"'::jsonb, '"2026-08-08T15:28:11.319Z"'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.novels ("id", "author_uid", "author_name", "author_photo", "title", "genre", "summary", "cover_image", "status", "likes_count", "views_count", "shares_count", "language", "violence_level", "moral_tone", "font_family", "font_size", "text_align", "line_height", "previous_part_id", "terabox_link", "created_at", "updated_at") VALUES ('n_002', 'user_sara_02', 'سارة النجار', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150', 'سر السراديب المعتمة', 'mystery', 'تحقيق غامض في مدينة أندلسية قديمة يكشف عن شبكة من الأسرار والرموز التاريخية المخبأة منذ قرون خلف الجدران العتيقة.', 'https://images.unsplash.com/photo-1532012197267-da84d127e765?q=80&w=800', 'published', 98, 1751, 21, 'ar', 'none', 'suspense', 'var(--font-serif)', '1.125rem', 'right', '1.75', NULL, '', '"2026-08-08T15:28:11.319Z"'::jsonb, '"2026-08-08T15:28:11.319Z"'::jsonb) ON CONFLICT DO NOTHING;

-- Data for table: chapters (7 rows)
INSERT INTO public.chapters ("id", "novel_id", "title", "content", "description", "order", "created_at", "updated_at") VALUES ('c_001', 'n_001', 'الفصل الأول: البداية في أطلال الرماد', 'كانت الرياح تعصف بشدة فوق أسوار قلعة الضباب العتيقة. جلس أدهم فوق الصخرة العالية يرقب أفق المدينة الممتد تحت ضوء القمر الفضي. لم يكن القتال مجرد خيار بالنسبة له، بل كان واجباً محتوماً لقومه الذين انتظروا العودة لسنوات طويلة. وقف وبيده سيفه المحفور عليه الرموز القديمة، جاهزاً لمواجهة أخطار الغد.', 'بداية رحلة أدهم وحكايته في القلعة العتيقة.', 1, '"2026-08-08T15:28:11.322Z"'::jsonb, '"2026-08-08T15:28:11.322Z"'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.chapters ("id", "novel_id", "title", "content", "description", "order", "created_at", "updated_at") VALUES ('c_002', 'n_001', 'الفصل الثاني: همس الرياح الساطعة', 'دخل أدهم إلى الممر المظلم أسفل القلعة، حيث تفوح رائحة القدم والأسرار. سرعان ما سمع صوتاً خافتاً يناديه باسمه القديم. التفت يميناً فرأى نقشاً مضيئاً على الجدار يرمز للعرش المفقود...', 'استكشاف السراديب واكتشاف الخريطة المخفية.', 2, '"2026-08-08T15:28:11.322Z"'::jsonb, '"2026-08-08T15:28:11.322Z"'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.chapters ("id", "novel_id", "title", "content", "description", "order", "created_at", "updated_at") VALUES ('c_003', 'n_001', 'الفصل الثالث: الفارس والأحجار السبعة', 'بدأت الرحلة الحقيقية نحو وادي الأسرار. جمع أدهم رفاقه السبعة في الفجر للبدء في البحث عن الأحجار السحرية.', 'تجميع الرفاق وتحديد الخطة الأولى.', 3, '"2026-08-08T15:28:11.322Z"'::jsonb, '"2026-08-08T15:28:11.322Z"'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.chapters ("id", "novel_id", "title", "content", "description", "order", "created_at", "updated_at") VALUES ('c_004', 'n_002', 'الفصل الأول: جريمة في القصر الأثري', 'في ليلة ممطرة، تسلل المفتش فريد إلى مكتبة القصر الأندلسي بعد تلقيه بلاغاً غامضاً عن اختفاء المخطوطة النادرة. وجد الباب مفتوحاً والأوراق مبعثرة على الأرض بشكل يثير الريبة.', 'بداية التحقيق الغامض واكتشاف المخطوطة المفقودة.', 1, '"2026-08-08T15:28:11.322Z"'::jsonb, '"2026-08-08T15:28:11.322Z"'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.chapters ("id", "novel_id", "title", "content", "description", "order", "created_at", "updated_at") VALUES ('c_005', 'n_002', 'الفصل الثاني: الرسالة المجهولة', 'عثر فريد بين طيات الكتب على مغلف أسود مغلق بالشمع الأحمر، مكتوب عليه عبارة واحدة باللغة القديمة.', 'تحليل الرسالة وتتبع الخيوط الأولى.', 2, '"2026-08-08T15:28:11.322Z"'::jsonb, '"2026-08-08T15:28:11.322Z"'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.chapters ("id", "novel_id", "title", "content", "description", "order", "created_at", "updated_at") VALUES ('c_006', 'n_003', 'الفصل الأول: رحيل ناعم', 'في زاوية ذلك المقهى الهادئ، جلست مريم تسجل خاطراتها في مفكرتها الصغيرة. لم تكن تعلم أن هذا اليوم سيغير مجرى حياتها بالكامل.', 'لقاء مريم الأول وبداية التغير الكبير.', 1, '"2026-08-08T15:28:11.322Z"'::jsonb, '"2026-08-08T15:28:11.322Z"'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.chapters ("id", "novel_id", "title", "content", "description", "order", "created_at", "updated_at") VALUES ('c_007', 'n_004', 'الفصل الأول: الإشارة الأولى من المجرة', 'تلقت المحطة الفضائية الرئيسية إشارة تردد غريبة قادمة من النظام الشمسي المجاور. قرر القائد طارق تجهيز المركبة للرحلة الاستكشافية.', 'انطلاق المركبة الفضائية الاستكشافية.', 1, '"2026-08-08T15:28:11.322Z"'::jsonb, '"2026-08-08T15:28:11.322Z"'::jsonb) ON CONFLICT DO NOTHING;

-- Data for table: characters (3 rows)
INSERT INTO public.characters ("id", "novel_id", "name", "role", "traits", "description", "created_at") VALUES ('char_01', 'n_001', 'الفارس أدهم', 'main', 'شجاع، نبيـل، حكيم', 'البطل الرئيسي، فارس مقدام يسعى لإعادة العرش والحفاظ على سلامة قومه.', '"2026-08-08T15:28:11.324Z"'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.characters ("id", "novel_id", "name", "role", "traits", "description", "created_at") VALUES ('char_02', 'n_001', 'الحكيم إدريس', 'supporting', 'غريب الأطوار، خبير بالرموز', 'مرشد أدهم في رحلته ومكتشف الخرائط القديمة.', '"2026-08-08T15:28:11.324Z"'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.characters ("id", "novel_id", "name", "role", "traits", "description", "created_at") VALUES ('char_03', 'n_002', 'المُحقق فريد', 'main', 'ذكي، دقيق الملاحظة', 'مفتش خبير في القضايا التاريخية والألغاز المعقدة.', '"2026-08-08T15:28:11.324Z"'::jsonb) ON CONFLICT DO NOTHING;

-- Data for table: world_notes (2 rows)
INSERT INTO public.world_notes ("id", "novel_id", "title", "category", "content", "created_at") VALUES ('wn_01', 'n_001', 'خريطة الممالك السبع', 'geography', 'تتكون الأرض القديمة من سبع ممالك تحيط بالبحيرة الفضية، وتحدها القلاع المنيعة من الشمال.', '"2026-08-08T15:28:11.326Z"'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.world_notes ("id", "novel_id", "title", "category", "content", "created_at") VALUES ('wn_02', 'n_001', 'نظام السحر والأحجار', 'magic', 'يعتمد السحر على سبعة أحجار كريمة متوازنة يمثل كل حجر منها عنصراً من عناصر الطبيعة.', '"2026-08-08T15:28:11.326Z"'::jsonb) ON CONFLICT DO NOTHING;

-- Data for table: follows (3 rows)
INSERT INTO public.follows ("id", "follower_uid", "followed_uid", "created_at") VALUES ('f_01', 'user_omar_03', 'user_master_01', '"2026-08-08T15:28:11.375Z"'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.follows ("id", "follower_uid", "followed_uid", "created_at") VALUES ('f_02', 'user_omar_03', 'user_sara_02', '"2026-08-08T15:28:11.375Z"'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.follows ("id", "follower_uid", "followed_uid", "created_at") VALUES ('f_03', 'user_layla_04', 'user_master_01', '"2026-08-08T15:28:11.375Z"'::jsonb) ON CONFLICT DO NOTHING;

-- Data for table: library (2 rows)
INSERT INTO public.library ("id", "uid", "novel_id", "added_at") VALUES ('lib_01', 'user_omar_03', 'n_001', '"2026-08-08T15:28:11.379Z"'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.library ("id", "uid", "novel_id", "added_at") VALUES ('lib_02', 'user_omar_03', 'n_002', '"2026-08-08T15:28:11.379Z"'::jsonb) ON CONFLICT DO NOTHING;

-- Data for table: reading_progress (1 rows)
INSERT INTO public.reading_progress ("id", "uid", "novel_id", "last_chapter_id", "last_chapter_order", "updated_at") VALUES ('prog_01', 'user_omar_03', 'n_001', 'c_002', 2, '"2026-08-08T15:28:11.381Z"'::jsonb) ON CONFLICT DO NOTHING;

-- Data for table: comments (2 rows)
INSERT INTO public.comments ("id", "novel_id", "chapter_id", "author_uid", "author_name", "author_photo", "text", "created_at") VALUES ('com_01', 'n_001', 'c_001', 'user_omar_03', 'عمر الفاروق', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150', 'بداية ملحمية مشوقة جداً! أسلوب السرد رائع والأحداث متسارعة.', '"2026-08-08T15:28:11.330Z"'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.comments ("id", "novel_id", "chapter_id", "author_uid", "author_name", "author_photo", "text", "created_at") VALUES ('com_02', 'n_001', 'c_001', 'user_sara_02', 'sara_author', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150', 'أبدعت يا أحمد، بانتظار الفصل القادم بشغف كبير!', '"2026-08-08T15:28:11.330Z"'::jsonb) ON CONFLICT DO NOTHING;

-- Data for table: likes (0 rows)

-- Data for table: notifications (2 rows)
INSERT INTO public.notifications ("id", "uid", "type", "title", "body", "read", "created_at") VALUES ('notif_01', 'user_master_01', 'comment', 'تعليق جديد', 'قام عمر الفاروق بالتعليق على روايتك "ظل العرش المفقود"', false, '"2026-08-08T15:28:11.384Z"'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.notifications ("id", "uid", "type", "title", "body", "read", "created_at") VALUES ('notif_02', 'user_master_01', 'follow', 'متابع جديد', 'بدأت سارة النجار بمتابعة حسابك', false, '"2026-08-08T15:28:11.384Z"'::jsonb) ON CONFLICT DO NOTHING;

